### ISSUE TITLE
Duplicated Entries under Categories

### ISSUE THREAD

**Issue by AlexT1259** [CamerapediaApp/Camerapedia-iOS#2]
Duplicated Entires:
Medium format and Medium Format under Sensor Size
APS-C and APS-C under Sensor Size 
Large sensor compact and Large Sensor Compact under Body Type

App Version: 3.2.1 Pro Version (3693)
Device: iPhone14,5 / iOS 17.2.1

**Comment by CamerapediaApp** [comment]
Fixed in Ver. 3.3.0
