### ISSUE TITLE
Search page displays Chinese secondary texts for result entries 

### ISSUE THREAD

**Issue by AlexT1259** [CamerapediaApp/Camerapedia-iOS#5]
![image0](https://github.com/CamerapediaApp/Camerapedia-iOS/assets/63884898/fa7d0501-d9d5-4300-8748-1fe9724e3cd6)

App Version: 3.2.1 Pro Version (3693)
Device: iPhone14,5 / iOS 17.2.1
App Language: English

**Comment by CamerapediaApp** [comment]
Fixed in Ver. 3.3.0
