### ISSUE TITLE
Not unified data-rate units for USB speed

### ISSUE THREAD

**Issue by AlexT1259** [CamerapediaApp/Camerapedia-iOS#7]
```
10 GBit/sec
    ^
5 GBit/sec
   ^
480 Mbit/sec
``` 
Correct unit should always be GB/s or Gbit/s, there is no such thing as GBit/s. Or, use Gbps or Mbps.

**Comment by CamerapediaApp** [comment]
Thank you @AlexT1259! This issue will be fixed in next release!
